package com.ftn.sbnz.model.models;

import javax.persistence.Entity;

public enum Symptom {
    HEADLIGHTS_ON,
    HEADLIGHTS_FLUCTUATE,
    NO_START,
    START,
    CRANKING,
    PERIODICALLY_CRANKING,
    EMPTY_TANK,
    NOT_EMPTY_TANK,
    UNCERTAIN_AMOUNT_OF_GAS,
    FLOODED,
    FUEL_SCENT,
    PERIODICALLY_FUEL_SCENT,
    FLAT_TIRE,
    DAMAGED_TIRE,
    TIRE_VIBRATING,
    DIFFICULT_STEERING,
    PULLING_TO_SIDE,
    WEIRD_NOISE_ACCELERATION,
    HIGH_ENGINE_TEMP,
    WHITE_SMOKE,
    LOW_COOLING_LIQUID,
    UNUSUAL_NOISE,
    HESITATION,
    JERKING,

   ELECTRICAL_CODE_A,
    ELECTRICAL_CODE_B,
    ELECTRICAL_CODE_C,
    ELECTRICAL_CODE_D
}
