package com.ftn.sbnz.model.models;

public enum Symptom {
    HEADLIGHTS_ON,
    HEADLIGHTS_FLUCTUATE,
    NO_START,
    START,
    CRANKING,
    EMPTY_TANK,
    NOT_EMPTY_TANK,
    FLOODED,
    FUEL_SCENT,
    FLAT_TIRE,
    DAMAGED_TIRE,
    TIRE_VIBRATING,
    DIFFICULT_STEERING,
    PULLING_TO_SIDE,
    WEIRD_NOISE_ACCELERATION,
    HIGH_ENGINE_TEMP,
    WHITE_SMOKE,
    LOW_COOLING_LIQUID,
    UNUSUAL_NOISE
}
